"""empty message

Revision ID: 34d27228a254
Revises: 4c420b3c444a
Create Date: 2017-11-22 16:25:50.466762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34d27228a254'
down_revision = '4c420b3c444a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_student_parents', 'parents_to_student', ['user_id_parent', 'user_id_student'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_student_parents', 'parents_to_student', type_='unique')
    # ### end Alembic commands ###
