"""empty message

Revision ID: 3c54840c9a37
Revises: f90443b2e270
Create Date: 2017-11-25 18:03:44.009321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c54840c9a37'
down_revision = 'f90443b2e270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('educationPlan_id', sa.Integer(), nullable=True),
    sa.Column('lessonNumber', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['educationPlan_id'], ['education_plan.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'education_plan', sa.Column('date', sa.DateTime(), nullable=True))
    op.drop_constraint(u'_year_semester', 'education_plan', type_='unique')
    op.create_unique_constraint('_year_semester', 'education_plan', ['date', 'semester'])
    op.drop_column(u'education_plan', 'year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'education_plan', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('_year_semester', 'education_plan', type_='unique')
    op.create_unique_constraint(u'_year_semester', 'education_plan', ['year', 'semester'])
    op.drop_column(u'education_plan', 'date')
    op.drop_table('schedule')
    # ### end Alembic commands ###
