"""empty message

Revision ID: 414e56efb3c0
Revises: 
Create Date: 2017-11-14 23:38:00.910498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '414e56efb3c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('room_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'classes', 'classrooms', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'classes', type_='foreignkey')
    op.drop_column('classes', 'room_id')
    # ### end Alembic commands ###
