"""empty message

Revision ID: 4c420b3c444a
Revises: b46384a16c03
Create Date: 2017-11-22 16:03:20.414536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c420b3c444a'
down_revision = 'b46384a16c03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parents_to_student', sa.Column('user_id_student', sa.Integer(), nullable=True))
    op.drop_constraint(u'parents_to_student_user_id_studen_fkey', 'parents_to_student', type_='foreignkey')
    op.create_foreign_key(None, 'parents_to_student', 'users', ['user_id_student'], ['id'])
    op.drop_column('parents_to_student', 'user_id_studen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parents_to_student', sa.Column('user_id_studen', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'parents_to_student', type_='foreignkey')
    op.create_foreign_key(u'parents_to_student_user_id_studen_fkey', 'parents_to_student', 'users', ['user_id_studen'], ['id'])
    op.drop_column('parents_to_student', 'user_id_student')
    # ### end Alembic commands ###
