"""empty message

Revision ID: b46384a16c03
Revises: 53ab9b600882
Create Date: 2017-11-22 15:53:10.306280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b46384a16c03'
down_revision = '53ab9b600882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parents_to_student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_parent', sa.Integer(), nullable=True),
    sa.Column('user_id_studen', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id_parent'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id_studen'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parents_to_student')
    # ### end Alembic commands ###
