"""empty message

Revision ID: b59b5ea7a3a0
Revises: 3c54840c9a37
Create Date: 2017-11-25 18:13:10.341372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b59b5ea7a3a0'
down_revision = '3c54840c9a37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('educationPlan_id', sa.Integer(), nullable=True),
    sa.Column('lessonNumber', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['educationPlan_id'], ['education_plan.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('typeOfWork_id', sa.Integer(), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['typeOfWork_id'], ['types_of_work.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('schedule')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('classroom_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('educationPlan_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lessonNumber', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['class_id'], [u'classes.id'], name=u'schedule_class_id_fkey'),
    sa.ForeignKeyConstraint(['classroom_id'], [u'classrooms.id'], name=u'schedule_classroom_id_fkey'),
    sa.ForeignKeyConstraint(['educationPlan_id'], [u'education_plan.id'], name=u'schedule_educationPlan_id_fkey'),
    sa.ForeignKeyConstraint(['subject_id'], [u'subjects.id'], name=u'schedule_subject_id_fkey'),
    sa.ForeignKeyConstraint(['teacher_id'], [u'users.id'], name=u'schedule_teacher_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'schedule_pkey')
    )
    op.drop_table('grades')
    op.drop_table('schedules')
    # ### end Alembic commands ###
