"""empty message

Revision ID: e8d8e3a22ab8
Revises: 34d27228a254
Create Date: 2017-11-25 17:32:42.136913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8d8e3a22ab8'
down_revision = '34d27228a254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'semester', name='_year_semester')
    )
    op.create_table('types_of_work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_constraint(u'parents_to_student_user_id_student_fkey', 'parents_to_student', type_='foreignkey')
    op.create_foreign_key(None, 'parents_to_student', 'users', ['user_id_student'], ['id'])
    op.drop_constraint(u'students_in_class_user_id_studen_fkey', 'students_in_class', type_='foreignkey')
    op.create_foreign_key(None, 'students_in_class', 'users', ['user_id_studen'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students_in_class', type_='foreignkey')
    op.create_foreign_key(u'students_in_class_user_id_studen_fkey', 'students_in_class', 'users', ['user_id_studen'], ['id'], ondelete=u'CASCADE')
    op.drop_constraint(None, 'parents_to_student', type_='foreignkey')
    op.create_foreign_key(u'parents_to_student_user_id_student_fkey', 'parents_to_student', 'users', ['user_id_student'], ['id'], ondelete=u'CASCADE')
    op.drop_table('types_of_work')
    op.drop_table('education_plan')
    # ### end Alembic commands ###
